max_steps: 1000
max_time_hours: null # train for at most this many hours
val_check_interval: 400
val_batches: 200
precision: 16-mixed
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
lr_warmup: 1000
lr_decay: linear
lr: 0.0001
weight_decay: 0.01
batch_size: 64
compile: False
log_bits_per_byte: False

dataloader_workers: 4
tokenizer_batch_size: 100 # this is the batch size for parellelism in the huggingface dataset, not the standard batch size
prefetch_factor: 2

